language:
  - cpp

cache:
  directories:
  - $HOME/.cache/pip

matrix:
  include:
    - os: osx
      osx_image: xcode8.3

before_install:
  - brew install hdf5 libmatio
  - pip install getgist

script:
  - echo 'done'
