language:
  - cpp

cache:
  directories:
  - $HOME/.cache/pip

matrix:
  include:
    - os: osx
      osx_image: xcode8.3

before_install:
  - brew install hdf5 libmatio
  - brew upgrade python
  - pip install getgist
  - getgist massich test_libmatio.cc  
  - wget "https://web.uvic.ca/~monahana/eos225/poc_data.mat.sfx"

script:
  - cc test_libmatio.cc -o mat -lmatio
  - ./mat poc_data.mat.sfx
